version: "3"
services:
  cra:
    build:
      context: .
      dockerfile: cra.Dockerfile
    labels:
      - "traefik.http.routers.cra.rule=Host(`cra.tangzhenming.com`)"
    container_name: cra

networks:
  default:
    external:
      name: my_traefik_default